deejay-hub/timeline-lwc

README.md, force-app/main/default/labels/CustomLabels.labels-meta.xml, force-app/main/default/lwc/timeline/timeline.html, force-app/main/default/lwc/timeline/timeline.js
Added translatable labels for Apply and Cancel that were missing and updated the button attributes to use the labels
=> Added labels for apply and cancel

force-app/main/default/lwc/timeline/timeline.js-meta.xml
@deejay-hub  I have included targets for lightningCommunity__Page and lightningCommunity__Default. I have also included recordId as the property to bind in Communities.
=> Communities Support included for Issue#17

force-app/main/default/lwc/timeline/timeline.js
Added zoom onEnd function to ensure that when a user clicks in the minimap zoom area but does not continue the drag operation that the handles are not left as a 'blob' as per issue #19 
Now the zoom boundary defaults to 14 days from the click area to make sure it is always visible to the user
=> Zoom boundary click fix - issue 19

force-app/main/default/labels/CustomLabels.labels-meta.xml, force-app/main/default/lwc/timeline/timeline.html, force-app/main/default/lwc/timeline/timeline.js
Added a select all and deselect all option to the filter panel. Closes #20
=> Filtering improvements

force-app/main/default/customMetadata/Timeline_Configuration.Contact_Assets.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Contact_CampaignMembers.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Contact_LiveChatTranscripts.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Contact_MessagingSessions.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Contact_WorkOrders.md-meta.xml
Added Work Order, Asset, Chat Transcript and Messaging Session
=> Support for additional child objects

force-app/main/default/classes/TimelineService.cls
=> Fixed reserved identifier

force-app/main/default/objects/Timeline_Configuration__mdt/listViews/Active_Configurations.listView-meta.xml, force-app/main/default/objects/Timeline_Configuration__mdt/listViews/Test_Configurations.listView-meta.xml
Added active and test list views
=> Added list views

.gitignore
Ignore PMD cache from the plugin
=> Ignore PMD cache

force-app/main/default/lwc/timeline/timeline.js-meta.xml
Adjusted minimum zoom property to 7 days from 15 days
=> Adjusted zoom minimum value

force-app/main/default/classes/TimelineService.cls-meta.xml, force-app/main/default/classes/TimelineService_Test.cls-meta.xml, force-app/main/default/lwc/illustration/illustration.js-meta.xml, force-app/main/default/lwc/timeline/timeline.js-meta.xml
API version updates for Summer '20
=> summer-20-api update

README.md
Added readme acknowledgement to use pmd. Ruleset included in repo
=> Added PMD utility

force-app/main/default/classes/TimelineService.cls, force-app/main/default/customMetadata/Timeline_Configuration.Person_Assets_Account.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_Assets_Contact.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_CampaignMembers.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_Cases_Account.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_Cases_Contact.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_EventRelations.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_Events_Account.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_Events_Contact.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_Files.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_LiveChatTranscripts_Account.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_LiveChatTranscripts_Contact.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_MessagingSessions_Account.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_MessagingSessions_Contact.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_Opportunities.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_OpportunityContactRoles.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_TaskRelations.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_Tasks_Account.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_Tasks_Contact.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_WorkOrders_Account.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_WorkOrders_Contact.md-meta.xml
Added missing relationships to timeline_mdt
Added fix for deduplication
=> Person Account Support Fixes

force-app/main/default/labels/CustomLabels.labels-meta.xml, force-app/main/default/lwc/timeline/timeline.js
Added the ability to translate the toast message including substitution value.
=> Translatable labels added

force-app/main/default/lwc/timeline/timeline.js-meta.xml
Since there is another LWC called Timeline we'll prepare to give this component a more unique name
=> Rebrand Master Label to Time Warp

force-app/main/default/classes/TimelineParentPicklist.cls, force-app/main/default/lwc/timeline/timeline.html, force-app/main/default/lwc/timeline/timeline.js, force-app/main/default/lwc/timeline/timeline.js-meta.xml
Updated lwc properties to ensure Parent Field didn't stop the lwc from rendering in a community
=> Communities update for Parent Field

force-app/main/default/classes/TimelineParentPicklist_Test.cls, force-app/main/default/customMetadata/Timeline_Configuration.Account_WorkOrders.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Case_WorkOrders.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Contact_WorkOrders.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_WorkOrders_Account.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_WorkOrders_Contact.md-meta.xml, sfdx-project.json
Bug fixes for tests failing in Orgs where the Contacts tab was renamed. Removed Work Orders as active by default.
=> Test patch

force-app/main/default/classes/TimelineParentPicklist.cls-meta.xml, force-app/main/default/classes/TimelineParentPicklist_Test.cls-meta.xml, force-app/main/default/classes/TimelineService.cls-meta.xml, force-app/main/default/classes/TimelineService_Test.cls-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Asset_WorkOrders.md-meta.xml, force-app/main/default/lwc/illustration/illustration.js-meta.xml, force-app/main/default/lwc/timeline/timeline.js-meta.xml
=> Api version incremented

force-app/main/default/classes/TimelineService.cls
Added support for OpenActivity and ActivityHistory to help with indirect tasks related to Account. Closes #119
=> Enhanced activity support

force-app/main/default/classes/TimelineService.cls, force-app/main/default/lwc/timeline/timeline.js
Added a check for subtype task type of event to support cases where someone wants to plot OpenActivities or ActivityHistories
=> Email call fix

.pmdruleset.xml, force-app/main/default/classes/TimelineService.cls, force-app/main/default/lwc/timeline/timeline.js
Updated PMD rules based on newer version
=> Pmd rule update

force-app/main/default/lwc/timeline/timeline.js
Added defensive code to prevent css styling issues with flexi region info
=> Default width with defensive code

config/project-scratch-def.json, force-app/main/default/customMetadata/Timeline_Configuration.Account_ActivityHistory.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Account_OpenActivities.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Contact_CampaignMembers_Test.md-meta.xml, force-app/main/default/objectTranslations/Task-en_US/Task-en_US.objectTranslation-meta.xml, force-app/main/default/translations/fr.translation-meta.xml, sfdx-project.json
=> Final package release

force-app/main/default/classes/TimelineParentPicklist.cls, force-app/main/default/lwc/timeline/timeline.css, force-app/main/default/lwc/timeline/timeline.js
- Removed unnecessary CSS
- Removed 2 nodes per plotted record to decrease DOM elements
- Removed unused CSS
=> Performance fixes

force-app/main/default/classes/TimelineParentPicklist.cls, force-app/main/default/customMetadata/Timeline_Configuration.Account_ActivityHistory.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Account_Events.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Account_OpenActivities.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Account_Tasks.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Asset_Events.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Asset_Tasks.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Case_Events.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Case_Tasks.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Contact_EventRelations.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Contact_Events.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Contact_TaskRelations.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Contact_Tasks.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Contact_Tasks_Test.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Lead_EventRelations.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Lead_Events.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Lead_TaskRelations.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Lead_Tasks.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Opportunity_Events.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Opportunity_Tasks.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_EventRelations.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_Events_Account.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_Events_Contact.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_TaskRelations.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_Tasks_Account.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.Person_Tasks_Contact.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.WorkOrder_Events.md-meta.xml, force-app/main/default/customMetadata/Timeline_Configuration.WorkOrder_Tasks.md-meta.xml, force-app/main/default/lwc/timeline/timeline.css, force-app/main/default/lwc/timeline/timeline.js
Updated event and task fallback fields to remove references to large text area fields
=> Large text fix

.prettierignore, force-app/main/default/classes/TimelineService.cls, force-app/main/default/lwc/timeline/timeline.html, force-app/main/default/lwc/timeline/timeline.js
Update to allow dates to be plotted based on locale not UTC time
=> Date format fixes

force-app/main/default/lwc/timeline/timeline.js-meta.xml
Add the following dat time ranges 0.25, 0.5, 1, 1.5, 2, 3, 4, 5, 6, 7, 8, 9, 10
=> Updated time range

force-app/main/default/classes/TimelineService.cls, force-app/main/default/layouts/Timeline_Configuration__mdt-Timeline Configuration Layout.layout-meta.xml, force-app/main/default/objects/Timeline_Configuration__mdt/fields/Inclusion_Field__c.field-meta.xml
Added inclusion field to metadata and the ability to optionally include/exclude based on the result of the field returning true. Allows admins to add a formula field to the object to filter based on complex rules.
=> Added filter by relationship

force-app/main/default/classes/TimelineService.cls, force-app/main/default/lwc/timeline/timeline.js, package-lock.json, package.json
- Updated node package versions
- Prettier formatting updates
=> Formatting and dependency updates

force-app/main/default/classes/TimelineService.cls, force-app/main/default/layouts/Timeline_Configuration__mdt-Timeline Configuration Layout.layout-meta.xml, force-app/main/default/lwc/timeline/timeline.js, force-app/main/default/objects/Timeline_Configuration__mdt/fields/Position_End_Date_Field__c.field-meta.xml
Added span support via a configurable, optional end date field.
=> Minimal span timeline support.

force-app/main/default/lwc/timeline/timeline.js, force-app/main/default/lwc/timeline/timeline.js-meta.xml
Added ability to position the zoom to the first activity found
=> feat-first-activity

force-app/main/default/lwc/timeline/timeline.js, force-app/main/default/lwc/timeline/timeline.js-meta.xml, package.json
=> Chore security

force-app/main/default/lwc/timeline/timeline.js, force-app/main/default/lwc/timeline/timeline.js-meta.xml, package.json
Fix icelandic data formatting in Chrome by overriding LOCALE
=> Bug icelandic dates

README.md
I just made a very small change in FAQ's first question nothing technical.
=> 📝 Update FAQ section first question from "to" --"do"

force-app/main/default/lwc/timeline/timeline.js, force-app/main/default/lwc/timeline/timeline.js-meta.xml
=> feat: date

force-app/main/default/lwc/timeline/timeline.js, force-app/main/default/translations/ar.translation-meta.xml, force-app/main/default/translations/de.translation-meta.xml, force-app/main/default/translations/es.translation-meta.xml, force-app/main/default/translations/fr.translation-meta.xml, force-app/main/default/translations/hi.translation-meta.xml, force-app/main/default/translations/it.translation-meta.xml, force-app/main/default/translations/iw.translation-meta.xml, force-app/main/default/translations/ja.translation-meta.xml, force-app/main/default/translations/ko.translation-meta.xml, force-app/main/default/translations/no.translation-meta.xml, force-app/main/default/translations/pt_BR.translation-meta.xml, force-app/main/default/translations/sv.translation-meta.xml, force-app/main/default/translations/th.translation-meta.xml, force-app/main/default/translations/zh_CN.translation-meta.xml, force-app/main/default/translations/zh_TW.translation-meta.xml
Error display with ability to refresh parent tab
=> Console Tab Error Fix

force-app/main/default/classes/TimelineService.cls, force-app/main/default/lwc/timeline/timeline.js
Adds support to OpenActivity and ActivityHistory to drilldown to EmailMessage record instead of Task
=> feat: emailmessage drilldown
